Models/Ballance.cs
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kendo.Mvc.Grid.CRUD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ballance
    {
        public int ID { get; set; }
        public long Start { get; set; }
        public long Finish { get; set; }
    }
}

Controllers/BallanceController.cs
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Web.Mvc;
using Kendo.Mvc.Grid.CRUD.Models;
using Kendo.DynamicLinq;
using System.Data.Entity.Validation;
using System.Data.Entity.Infrastructure;
using System.Diagnostics;

namespace TestTask
{
    public class BallanceController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }
       
        [HttpPost]
        public ActionResult Read(int take, int skip, IEnumerable<Sort> sort, Kendo.DynamicLinq.Filter filter)
        {
            using (var northwind = new Northwind())
            {
                var r = northwind.Getbalances().ToList<Ballance>().AsQueryable();
                var result = r
                    .OrderBy(p => p.ID)                     
                    .Select(p => new BallanceViewModel
                    {   ID = p.ID,                     
                        Start = p.Start,
                        Finish = p.Finish                        
                    }).ToDataSourceResult(take, skip, sort, filter);
                return Json(result);
            }
        }    
    }
}

Views/Ballance/Index.cshtml
@section HeaderSection {
    <link href="http://cdn.kendostatic.com/2012.3.1114/styles/kendo.common.min.css" rel="stylesheet" />
    <link href="http://cdn.kendostatic.com/2012.3.1114/styles/kendo.default.min.css" rel="stylesheet" />
    <script src="http://cdn.kendostatic.com/2012.3.1114/js/kendo.all.min.js"></script>
}
<h2>Остатки свободных номеров</h2>
<div id="grid"></div>
<script>
$(function () {
    $("#grid").kendoGrid({
        width: "350px",
        columns: [            
            { field: "Start", width: "150px", sortable: true },
            { field: "Finish", width: "150px" },                     
        ],
        sort: { field: "Comment", dir: "desc" },
        editable: "popup",        
        pageable: true,
        sortable: true,
        filterable: true,        
        dataSource: {
            serverPaging: true,
            serverFiltering: true,
            serverSorting: true,
            pageSize: 30,
            schema: {
                data: "Data",
                total: "Total",
                model: {
                    id: "ID",
                    fields: {
                        ID: { editable: false, nullable: true },                        
                        Start:  { type: "number", validation: { min: 1000000000, max:99999999999, required: true } },
                        Finish: { type: "number", validation: { min: 1000000000, max: 99999999999, required: true } }
                    }
                }
            },            
            transport: {               
                read: {
                    url: "@Url.Action("Read", "Ballance")", 
                    contentType: "application/json",
                    type: "POST" 
                },                
                parameterMap: function(data, operation) {
                    if (operation != "read") {
                        var result = {};

                        for (var i = 0; i < data.models.length; i++) {
                            var product = data.models[i];
                            for (var member in product) {
                                result["applyings[" + i + "]." + member] = product[member];
                            }
                        }
                        return result;
                    } else {
                        return JSON.stringify(data)
                    }
                }
            }
        }
    });
});
</script>