Models/Production.cs
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kendo.Mvc.Grid.CRUD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Production
    {
        public int ID { get; set; }
        public long Start { get; set; }
        public long Finish { get; set; }
        public string Comment { get; set; }
    }
}

Controllers/ProductionController.cs
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Web.Mvc;
using Kendo.Mvc.Grid.CRUD.Models;
using Kendo.DynamicLinq;
using System.Data.Entity.Validation;
using System.Data.Entity.Infrastructure;
using System.Diagnostics;

namespace TestTask
{
    public class ProductionController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(ProductionViewModel productionViewModel)
        {
            var result = new List<Production>();
            using (var northwind = new Northwind())
            {

                if (northwind.CanInsertProduction(productionViewModel.Start, productionViewModel.Finish).ElementAt(0).Value == 0)
                {
                    ModelState.AddModelError("error", "error");
                    return View();
                }

                var production = new Production
                {
                    Comment = productionViewModel.Comment,
                    Start = productionViewModel.Start,
                    Finish = productionViewModel.Finish
                };
                result.Add(production);
                northwind.Productions.Add(production);
                northwind.SaveChanges();

                return Json(result.Select(p => new ProductionViewModel
                {
                    ID = p.ID,
                    Comment = p.Comment,
                    Start = p.Start,
                    Finish = p.Finish
                })
                .ToList());
            }
        }

        [HttpPost]
        public ActionResult Read(int take, int skip, IEnumerable<Sort> sort, Kendo.DynamicLinq.Filter filter)
        {
            using (var northwind = new Northwind())
            {
                var result = northwind.Productions
                    .OrderBy(p => p.ID)
                    .Select(p => new ProductionViewModel
                    {
                        ID = p.ID,
                        Comment = p.Comment,
                        Start = p.Start,
                        Finish = p.Finish
                    })
                    .ToDataSourceResult(take, skip, sort, filter);

                return Json(result);
            }
        }

        [HttpPost]
        public ActionResult Update(ProductionViewModel productionViewModel)
        {
            using (var northwind = new Northwind())
            {
                /*
                if (northwind.CanInsertProduction(productionViewModel.Start, productionViewModel.Finish).ElementAt(0).Value == 0)
                {
                    ModelState.AddModelError("error", "error");
                    return View();
                }
                */
                var production = new Production
                {
                    ID = productionViewModel.ID,
                    Comment = productionViewModel.Comment,
                    Start = productionViewModel.Start,
                    Finish = productionViewModel.Finish
                };
                northwind.Productions.Attach(production);
                northwind.Entry(production).State = System.Data.EntityState.Modified;

                northwind.SaveChanges();
                return Json(null);
            }
        }

        [HttpPost]
        public ActionResult Destroy(ProductionViewModel productionViewModel)
        {
            using (var northwind = new Northwind())
            {
                var production = new Production
                {
                    ID = (int)productionViewModel.ID,
                };
                northwind.Productions.Attach(production);
                northwind.Productions.Remove(production);

                northwind.SaveChanges();
                return Json(null);
            }
        }

    }
}

Views/Production/Index.cshtml
@section HeaderSection {
    <link href="http://cdn.kendostatic.com/2012.3.1114/styles/kendo.common.min.css" rel="stylesheet" />
    <link href="http://cdn.kendostatic.com/2012.3.1114/styles/kendo.default.min.css" rel="stylesheet" />
    <script src="http://cdn.kendostatic.com/2012.3.1114/js/kendo.all.min.js"></script>
}
<h2>Производство продукции</h2>
@* The DIV where the Kendo grid will be initialized *@
<div id="grid"></div>
<script>
    function errorHandler(gridName) {     
        return function (e) {            
            alert("Диапазон неверный или пересекается с одним из существующих");
            var grid = $(gridName).data("grid");
            grid.cancelChanges();
        };
    }
$(function () {
    $("#grid").kendoGrid({
        
        columns: [
            "Comment",            
            { field: "Start", width: "150px", sortable: true },
            { field: "Finish", width: "150px" },            
            { command: ["edit", "destroy"], title: "&nbsp;", width: "250px" }
        ],
        sort: { field: "Comment", dir: "desc" },
        editable: "popup",        
        pageable: true,
        sortable: true,
        filterable: true,
        toolbar: ["create"],
        dataSource: {
            error: errorHandler("#grid"),
            serverPaging: true,
            serverFiltering: true,
            serverSorting: true,
            pageSize: 30,
            schema: {
                data: "Data",
                total: "Total",
                model: {
                    id: "ID",
                    fields: {
                        ID: { editable: false, nullable: true },
                        Comment: { validation: { required: true } },
                        Start:  { type: "number", validation: { min: 1000000000, max:9999999999, required: true } },
                        Finish: { type: "number", validation: { min: 1000000000, max:9999999999, required: true } }
                    }
                }
            },
            batch: false,
            transport: {
                create: {
                    url: "@Url.Action("Create", "Production")",
                    type: "POST"
                },
                read: {
                    url: "@Url.Action("Read", "Production")", 
                    contentType: "application/json",
                    type: "POST" 
                },
                update: {
                    url:"@Url.Action("Update", "Production")",
                    type: "POST" 
                },
                destroy: {
                    url: "@Url.Action("Destroy", "Production")",
                    type: "POST" 
                },                
                parameterMap: function (data, operation) {                  
                    if (operation != "read") {                     
                        return data;                     
                    } else {
                        return JSON.stringify(data)
                    }
                
                }
            }
        }
    });
});
</script>